### ISSUE TITLE
Create JSON file of dummy blog post objects

### ISSUE THREAD

**Issue by missbabelfish** [Hack-Weekly/indigo-turtle-blog#6]

**Comment by OwenTruong** [comment]
This issue is similar to writing test cases for our blog posts ^^
Each Post object in the JSON should follow the following type:
{
  author: string,
  date: "xxxx-yy-zz",
  title: string,
  content: string,
  tags: string[]
}

Examples of date: "2020-04-23", "2023-04-23", "0950-11-19"... Year 950 is a bit ridiculous, but did it as an example. Date should follow 4-digit year, then 2-digit month, then 2-digit day
